### ISSUE TITLE
Any particular reason to the protobuf version constraint >2.4.1?

### ISSUE THREAD

**Issue by bddppq** [spotify/snakebite#182]
Currently it requires protobuf > 2.4.1
Is there any particular reason? I'm asking this because we internally are using a customized protobuf, which is based on 2.4.1.

**Comment by wouterdebie** [comment]
Not completely sure why that was. Can you try running against your custom version?

**Comment by bddppq** [comment]
It works with our customized 2.4.1 version

**Comment by rajeshcode** [comment]
I was getting error as below any idea?
++++
$ python
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from snakebite.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/snakebite-2.11.0-py2.6.egg/snakebite/client.py", line 16, in <module>
    import snakebite.protobuf.ClientNamenodeProtocol_pb2 as client_proto
  File "/usr/lib/python2.6/site-packages/snakebite-2.11.0-py2.6.egg/snakebite/protobuf/ClientNamenodeProtocol_pb2.py", line 12, in <module>
    import Security_pb2
  File "/usr/lib/python2.6/site-packages/snakebite-2.11.0-py2.6.egg/snakebite/protobuf/Security_pb2.py", line 231, in <module>
    DESCRIPTOR.message_types_by_name['TokenProto'] = _TOKENPROTO
AttributeError: 'FileDescriptor' object has no attribute 'message_types_by_name'


++++
 python ./inject.py  host-namen-node 8030  user@DOMAIN.DOMAIN.COM hdfs "/bin/ls"
Traceback (most recent call last):
  File "./inject.py", line 3, in <module>
    from snakebite.client import Client
  File "/home/hadoop/poc/snakebite/client.py", line 16, in <module>
    import snakebite.protobuf.ClientNamenodeProtocol_pb2 as client_proto
  File "/home/hadoop/poc/snakebite/protobuf/ClientNamenodeProtocol_pb2.py", line 12, in <module>
    import Security_pb2
  File "/home/hadoop/poc/snakebite/protobuf/Security_pb2.py", line 231, in <module>
    DESCRIPTOR.message_types_by_name['TokenProto'] = _TOKENPROTO
AttributeError: 'FileDescriptor' object has no attribute ‘message_types_by_name'
++
